name: Buscar turnos COSEM

on:
  schedule:
    - cron: "*/10 * * * *"  # cada 10 minutos
  workflow_dispatch:

jobs:
  ejecutar:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          pip install selenium webdriver-manager requests

      - name: Ejecutar script
        env:
          EMAIL_REMITENTE: ${{ secrets.EMAIL_REMITENTE }}
          EMAIL_DESTINATARIO: ${{ secrets.EMAIL_DESTINATARIO }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_IDS }}
          USUARIO_COSEM: ${{ secrets.USUARIO_COSEM }}
          PASSWORD_COSEM: ${{ secrets.PASSWORD_COSEM }}
        run: python main.py

