# Esto es solo para reactivar, no afecta el código
# Última actualización: 25/06
name: Buscar turnos COSEM

on:
  schedule:
    - cron: '*/10 * * * *'
  workflow_dispatch:

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repo
        uses: actions/checkout@v3

      - name: Instalar Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.11

      - name: Instalar dependencias
        run: pip install -r requirements.txt

      - name: Ejecutar script
        env:
          EMAIL_REMITENTE: ${{ secrets.EMAIL_REMITENTE }}
          EMAIL_DESTINATARIO: ${{ secrets.EMAIL_DESTINATARIO }}
          EMAIL_PASSWORD: ${{ secrets.EMAIL_PASSWORD }}
          TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
          TELEGRAM_CHAT_IDS: ${{ secrets.TELEGRAM_CHAT_IDS }}
          USUARIO_COSEM: ${{ secrets.USUARIO_COSEM }}
          PASSWORD_COSEM: ${{ secrets.PASSWORD_COSEM }}
        run: python buscar_turno.py



