name: Buscar Turno Bot

on:
  schedule:
    - cron: '*/5 * * * *'  # cada 5 minutos
  workflow_dispatch:       # te permite ejecutarlo manualmente también

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: 3.10

    - name: Install dependencies
      run: pip install -r requirements.txt

    - name: Run bot
      env:
        TELEGRAM_TOKEN: ${{ secrets.TELEGRAM_TOKEN }}
        CHAT_ID: ${{ secrets.CHAT_ID }}
        URL: ${{ secrets.URL }}
      run: python idchat.py
